const DogBreeds = [
    { label: 'Afghan Hound', value: 'afghan_hound' },
    { label: 'Airedale Terrier', value: 'airedale_terrier' },
    { label: 'Akita', value: 'akita' },
    { label: 'Alaskan Malamute', value: 'alaskan_malamute' },
    { label: 'Australian Shepherd', value: 'australian_shepherd' },
    { label: 'Australian Terrier', value: 'australian_terrier' },
    { label: 'Basenji', value: 'basenji' },
    { label: 'Basset Hound', value: 'basset_hound' },
    { label: 'Beagle', value: 'beagle' },
    { label: 'Bedlington Terrier', value: 'bedlington_terrier' },
    { label: 'Belgian Malinois', value: 'belgian_malinois' },
    { label: 'Belgian Tervuren', value: 'belgian_tervuren' },
    { label: 'Bernese Mountain Dog', value: 'bernese_mountain_dog' },
    { label: 'Bichon Frise', value: 'bichon_frise' },
    { label: 'Border Collie', value: 'border_collie' },
    { label: 'Border Terrier', value: 'border_terrier' },
    { label: 'Boston Terrier', value: 'boston_terrier' },
    { label: 'Boxer', value: 'boxer' },
    { label: 'Bracco Italiano', value: 'bracco_italiano' },
    { label: 'Brittany', value: 'brittany' },
    { label: 'Bullmastiff', value: 'bullmastiff' },
    { label: 'Cairn Terrier', value: 'cairn_terrier' },
    { label: 'Cane Corso', value: 'cane_corso' },
    { label: 'Cavalier King Charles Spaniel', value: 'cavalier_king_charles_spaniel' },
    { label: 'Chihuahua', value: 'chihuahua' },
    { label: 'Chow Chow', value: 'chow_chow' },
    { label: 'Clumber Spaniel', value: 'clumber_spaniel' },
    { label: 'Cockapoo', value: 'cockapoo' },
    { label: 'Cocker Spaniel', value: 'cocker_spaniel' },
    { label: 'Coton de Tulear', value: 'coton_de_tulear' },
    { label: 'Dachshund', value: 'dachshund' },
    { label: 'Dalmatian', value: 'dalmatian' },
    { label: 'Dandie Dinmont Terrier', value: 'dandie_dinmont_terrier' },
    { label: 'Dogue de Bordeaux', value: 'dogue_de_bordeaux' },
    { label: 'English Setter', value: 'english_setter' },
    { label: 'English Springer Spaniel', value: 'english_springer_spaniel' },
    { label: 'Estrela Mountain Dog', value: 'estrela_mountain_dog' },
    { label: 'Finnish Lapphund', value: 'finnish_lapphund' },
    { label: 'Finnish Spitz', value: 'finnish_spitz' },
    { label: 'French Bulldog', value: 'french_bulldog' },
    { label: 'German Shepherd', value: 'german_shepherd' },
    { label: 'Golden Retriever', value: 'golden_retriever' },
    { label: 'Great Dane', value: 'great_dane' },
    { label: 'Greyhound', value: 'greyhound' },
    { label: 'Havanese', value: 'havanese' },
    { label: 'Irish Setter', value: 'irish_setter' },
    { label: 'Irish Terrier', value: 'irish_terrier' },
    { label: 'Irish Wolfhound', value: 'irish_wolfhound' },
    { label: 'Italian Greyhound', value: 'italian_greyhound' },
    { label: 'Jack Russell Terrier', value: 'jack_russell_terrier' },
    { label: 'Japanese Spitz', value: 'japanese_spitz' },
    { label: 'Keeshond', value: 'keeshond' },
    { label: 'Lagotto Romagnolo', value: 'lagotto_romagnolo' },
    { label: 'Labrador Retriever', value: 'labrador_retriever' },
    { label: 'Lhasa Apso', value: 'lhasa_apso' },
    { label: 'Leonberger', value: 'leonberger' },
    { label: 'Maltese', value: 'maltese' },
    { label: 'Miniature Schnauzer', value: 'miniature_schnauzer' },
    { label: 'Newfoundland', value: 'newfoundland' },
    { label: 'Norfolk Terrier', value: 'norfolk_terrier' },
    { label: 'Norwegian Elkhound', value: 'norwegian_elkhound' },
    { label: 'Norwich Terrier', value: 'norwich_terrier' },
    { label: 'Old English Sheepdog', value: 'old_english_sheepdog' },
    { label: 'Papillon', value: 'papillon' },
    { label: 'Pekingese', value: 'pekingese' },
    { label: 'Petit Basset Griffon Vendéen', value: 'petit_basset_griffon_vendeen' },
    { label: 'Pharaoh Hound', value: 'pharaoh_hound' },
    { label: 'Pointer', value: 'pointer' },
    { label: 'Poodle', value: 'poodle' },
    { label: 'Pug', value: 'pug' },
    { label: 'Rottweiler', value: 'rottweiler' },
    { label: 'Saint Bernard', value: 'saint_bernard' },
    { label: 'Saluki', value: 'saluki' },
    { label: 'Samoyed', value: 'samoyed' },
    { label: 'Scottish Terrier', value: 'scottish_terrier' },
    { label: 'Shar Pei', value: 'shar_pei' },
    { label: 'Shih Tzu', value: 'shih_tzu' },
    { label: 'Siberian Husky', value: 'siberian_husky' },
    { label: 'Staffordshire Bull Terrier', value: 'staffordshire_bull_terrier' },
    { label: 'Sussex Spaniel', value: 'sussex_spaniel' },
    { label: 'Tibetan Spaniel', value: 'tibetan_spaniel' },
    { label: 'Tibetan Terrier', value: 'tibetan_terrier' },
    { label: 'Weimaraner', value: 'weimaraner' },
    { label: 'Welsh Terrier', value: 'welsh_terrier' },
    { label: 'West Highland White Terrier', value: 'west_highland_white_terrier' },
    { label: 'Whippet', value: 'whippet' },
    { label: 'Wirehaired Vizsla', value: 'wirehaired_vizsla' },
    { label: 'Yorkshire Terrier', value: 'yorkshire_terrier' },
  ];
  
  export default DogBreeds;
  